import type { LucideIcon } from 'lucide-react';
import {
  Accessibility,
  Activity,
  SlidersHorizontal,
  Ambulance,
  Archive,
  ArrowLeft,
  ArrowRight,
  ArrowLeftRight,
  LayoutDashboard,
  Baby,
  Palmtree,
  Bed,
  Scan,
  Bone,
  Brain,
  Facebook,
  Dribbble,
  Linkedin,
  MapPin,
  Twitter,
  MessageCircle,
  Briefcase,
  Building,
  Building2,
  Hospital,
  CalendarCheck,
  CalendarX,
  CalendarClock,
  Car,
  GalleryHorizontal,
  Banknote,
  BadgeCheck,
  LineChart,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronsRight,
  CheckCircle,
  ClipboardList,
  Clock,
  Cloud,
  Download,
  Droplet,
  DropletOff,
  ExternalLink,
  Glasses,
  FileBadge,
  FileCheck,
  FileDown,
  FileText,
  Headset,
  Heart,
  HeartHandshake,
  HeartPulse,
  House,
  HousePlus,
  Info,
  SquareUser,
  Network,
  Wind,
  Mail,
  Map,
  MapPinned,
  MessagesSquare,
  Frown,
  Syringe,
  Newspaper,
  Phone,
  PhoneCall,
  PictureInPicture,
  Pill,
  Plug,
  Plus,
  Landmark,
  CircleDot,
  Puzzle,
  Quote,
  Receipt,
  RefreshCw,
  Rocket,
  Rss,
  PersonStanding,
  School,
  Send,
  Settings,
  ShieldCheck,
  ShieldPlus,
  Square,
  Star,
  Stethoscope,
  Sun,
  LayoutTemplate,
  Siren,
  User,
  UserCheck,
  UserRoundCheck,
  Users,
  Video,
  Footprints,
  WandSparkles,
  WifiOff,
  PenLine,
  X,
} from 'lucide-react';

const ICON_MAP: Record<string, LucideIcon> = {
  'tabler:accessible': Accessibility,
  'tabler:activity': Activity,
  'tabler:adjustments-horizontal': SlidersHorizontal,
  'tabler:ambulance': Ambulance,
  'tabler:archive': Archive,
  'tabler:arrow-left': ArrowLeft,
  'tabler:arrow-right': ArrowRight,
  'tabler:arrows-right-left': ArrowLeftRight,
  'tabler:artboard': LayoutDashboard,
  'tabler:baby-carriage': Baby,
  'tabler:beach': Palmtree,
  'tabler:bed': Bed,
  'tabler:body-scan': Scan,
  'tabler:bone': Bone,
  'tabler:brain': Brain,
  'tabler:brand-behance': Dribbble,
  'tabler:brand-dribbble': Dribbble,
  'tabler:brand-facebook': Facebook,
  'tabler:brand-linkedin': Linkedin,
  'tabler:brand-pinterest': MapPin,
  'tabler:brand-twitter': Twitter,
  'tabler:brand-whatsapp': MessageCircle,
  'tabler:brand-x': X,
  'tabler:briefcase': Briefcase,
  'tabler:building': Building,
  'tabler:building-community': Building2,
  'tabler:building-hospital': Hospital,
  'tabler:building-store': Building,
  'tabler:calendar-check': CalendarCheck,
  'tabler:calendar-off': CalendarX,
  'tabler:calendar-repeat': CalendarClock,
  'tabler:car': Car,
  'tabler:carousel-horizontal': GalleryHorizontal,
  'tabler:cash-banknote': Banknote,
  'tabler:certificate': BadgeCheck,
  'tabler:chart-line': LineChart,
  'tabler:check': Check,
  'tabler:chevron-down': ChevronDown,
  'tabler:chevron-left': ChevronLeft,
  'tabler:chevron-right': ChevronRight,
  'tabler:chevrons-right': ChevronsRight,
  'tabler:circle-check': CheckCircle,
  'tabler:clipboard-list': ClipboardList,
  'tabler:clock': Clock,
  'tabler:clock-24': Clock,
  'tabler:cloud': Cloud,
  'tabler:download': Download,
  'tabler:droplet': Droplet,
  'tabler:droplet-off': DropletOff,
  'tabler:external-link': ExternalLink,
  'tabler:eyeglass': Glasses,
  'tabler:file-certificate': FileBadge,
  'tabler:file-check': FileCheck,
  'tabler:file-download': FileDown,
  'tabler:file-text': FileText,
  'tabler:headset': Headset,
  'tabler:heart': Heart,
  'tabler:heart-handshake': HeartHandshake,
  'tabler:heart-rate-monitor': HeartPulse,
  'tabler:home': House,
  'tabler:home-check': HousePlus,
  'tabler:home-heart': HeartHandshake,
  'tabler:home-shield': ShieldPlus,
  'tabler:info-circle': Info,
  'tabler:info-square': Info,
  'tabler:layers-union': Puzzle,
  'tabler:lungs': Wind,
  'tabler:mail': Mail,
  'tabler:map-2': Map,
  'tabler:map-pin': MapPin,
  'tabler:map-search': MapPinned,
  'tabler:message-circle': MessageCircle,
  'tabler:messages': MessagesSquare,
  'tabler:mood-sad': Frown,
  'tabler:needle': Syringe,
  'tabler:network': Network,
  'tabler:news': Newspaper,
  'tabler:news-off': Newspaper,
  'tabler:phone': Phone,
  'tabler:phone-call': PhoneCall,
  'tabler:picture-in-picture': PictureInPicture,
  'tabler:pill': Pill,
  'tabler:plug-connected': Plug,
  'tabler:plus': Plus,
  'tabler:podium': Landmark,
  'tabler:point-filled': CircleDot,
  'tabler:puzzle': Puzzle,
  'tabler:quote': Quote,
  'tabler:receipt': Receipt,
  'tabler:refresh': RefreshCw,
  'tabler:rocket': Rocket,
  'tabler:rss': Rss,
  'tabler:run': PersonStanding,
  'tabler:school': School,
  'tabler:send': Send,
  'tabler:settings': Settings,
  'tabler:shield-check': ShieldCheck,
  'tabler:shield-heart': ShieldPlus,
  'tabler:square-number-1': Square,
  'tabler:square-number-2': Square,
  'tabler:square-number-3': Square,
  'tabler:square-number-4': Square,
  'tabler:square-rounded-arrow-right': ArrowRight,
  'tabler:star-filled': Star,
  'tabler:stethoscope': Stethoscope,
  'tabler:sun': Sun,
  'tabler:template': LayoutTemplate,
  'tabler:urgent': Siren,
  'tabler:user': User,
  'tabler:user-check': UserCheck,
  'tabler:user-heart': HeartHandshake,
  'tabler:user-star': UserRoundCheck,
  'tabler:users': Users,
  'tabler:video': Video,
  'tabler:walk': Footprints,
  'tabler:wand': WandSparkles,
  'tabler:wheelchair': Accessibility,
  'tabler:wifi-off': WifiOff,
  'tabler:writing': PenLine,
  'tabler:x': X,
  'tabler:external-link-off': ExternalLink,
  'tabler:square-user': SquareUser,
};

export function resolveIcon(name?: string): LucideIcon | null {
  if (!name) return null;
  return ICON_MAP[name] ?? null;
}
